/* Minimal UUIDPlugin for Pharo startup on Node/SqueakJS. */
function UUIDPlugin() {
  "use strict";

  function randomBytes16() {
    var bytes = new Uint8Array(16);
    try {
      if (typeof crypto === "object" && crypto && typeof crypto.getRandomValues === "function") {
        crypto.getRandomValues(bytes);
        return bytes;
      }
    } catch (_e) {}
    try {
      if (typeof require === "function") {
        require("crypto").randomFillSync(bytes);
        return bytes;
      }
    } catch (_e) {}
    for (var i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256) & 255;
    return bytes;
  }

  return {
    getModuleName: function() { return "UUIDPlugin"; },
    interpreterProxy: null,

    setInterpreter: function(anInterpreter) {
      this.interpreterProxy = anInterpreter;
      return true;
    },

    initialiseModule: function() { return true; },
    shutdownModule: function() { return true; },

    primitiveMakeUUID: function(argCount) {
      if (argCount !== 0) return false;
      var oop = this.interpreterProxy.stackValue(0);
      if (!oop || !oop.bytes || oop.bytes.length !== 16) return false;
      var bytes = randomBytes16();
      // RFC 4122 version-4/variant bits. Pharo only requires 16 generated bytes,
      // but setting these makes the emulated value a conventional UUID.
      bytes[6] = (bytes[6] & 0x0f) | 0x40;
      bytes[8] = (bytes[8] & 0x3f) | 0x80;
      for (var i = 0; i < 16; i++) oop.bytes[i] = bytes[i];
      this.interpreterProxy.popthenPush(1, oop);
      return true;
    }
  };
}

function registerUUIDPlugin() {
  if (typeof Squeak === "object" && Squeak.registerExternalModule) {
    Squeak.registerExternalModule("UUIDPlugin", UUIDPlugin());
  } else setTimeout(registerUUIDPlugin, 100);
}

registerUUIDPlugin();
