'use strict';

module.exports = {
  ...require('./core/value'),
  ...require('./core/components'),
  ...require('./core/inventory'),
  ...require('./core/patch'),
  ...require('./core/imperfections'),
  ...require('./core/serialization'),
  ...require('./core/design'),
  ...require('./core/designControls'),
  ...require('./core/designDiagnostics'),
  ...require('./core/designAccessories'),
  ...require('./core/designRepairs'),
  ...require('./core/designHistory'),
  ...require('./core/designUsability'),
  ...require('./core/designPanelPolish'),
  ...require('./core/designRuntime'),
  ...require('./core/designStorage'),
  ...require('./core/adoptedPatchPanelConnectors'),
  ...require('./core/adoptedPatchPanelEditor'),
  ...require('./core/designTemplates'),
  ...require('./core/physicalSockets'),
  ...require('./core/solver'),
  ...require('./core/modes'),
  ...require('./core/hybrid'),
  ...require('./core/multiboard'),
  ...require('./examples/dampedOscillation'),
  ...require('./examples/serializedGallery'),
  ...require('./examples/firstSteps'),
  ...require('./examples/scopeExpectations'),
  ...require('./examples/multiBoardDemo'),
  ...require('./examples/imperfectionDemo'),
};
